# Generated by Django 2.2.2 on 2019-07-16 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notions', models.SmallIntegerField(blank=True, null=True)),
                ('is_op', models.BooleanField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('thumbs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
